# Site settings
title: words, literally
email: anton@lyxit.se
description: > # this means to ignore newlines until "baseurl:"
  Words and code mixed together like a bland ol' sallad.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://antongunnarsson.se" # the base hostname & protocol for your site
twitter_username:
github_username:  anton-g

# Post settings
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
