name: words, literally
description: Words and code mixed together like a bland ol' sallad
meta_description: "Words and code mixed together like a bland ol' sallad"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://antongunnarsson.se'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://antongunnarsson.se'
author:         'Anton Gunnarsson'
