name: Anton Gunnarsson
description: Software developer and podcast host.
meta_description: "Anton is a software developer and podcast host."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: 'http://antongunnarsson.se'
google_analytics: 'UA-21600317-1'
gems: [jekyll-paginate]

url:            'http://antongunnarsson.se'
author:         'Anton'
authordescription: I work with programming at [Avanade](http://avanade.com), talk about life as a developer in the (swedish) podcast [Still in beta](http://stillinbeta.se) and every once in a while i try to write something here.

#post setup
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: /:title/
