name: words, literally
description: Words and code mixed together like a bland ol' sallad
meta_description: "Words and code mixed together like a bland ol' sallad"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://antongunnarsson.se'
google_analytics: 'UA-21600317-1'
gems: [jekyll-paginate]

url:            'http://antongunnarsson.se'
author:         'Anton'
authordescription: I make stuff over at [Lyxit](http://lyxit.se), study information systems in [Swedens fourth largest city](https://en.wikipedia.org/wiki/Uppsala) and writes about developer life.

#post setup
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: /:categories/:year/:month/:day/:title/
