import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styled, { keyframes } from 'styled-components'
import { EasterEgg } from '../components/EasterEgg'
import { Fireworks } from '../components/Fireworks'
import { saveSvgAsPng } from 'save-svg-as-png'

const WoopWoop: NextPage = () => {
  const [showEasterEgg, setShowEasterEgg] = useState(false)
  const [seed, setSeed] = useState(0)

  useEffect(() => {
    setShowEasterEgg(true)
  }, [])

  const saveEgg = () => {
    saveSvgAsPng(document.getElementById('easter-egg-svg'), 'egg.png')
  }

  console.log({ seed })

  return (
    <Wrapper>
      <Head>
        <title>🤫</title>
        <meta name="robots" content="noindex" />
      </Head>
      <Content>
        <button onClick={() => setSeed(Math.random() * 1000)}>debug</button>
        <Title>CONGRATS!</Title>
        <Subtitle>
          You found your own <strong>personal</strong> easter egg! It&apos;s
          been generated by your unique way to find it and won&apos;t look the
          same for anyone else!
        </Subtitle>
        <EggWrapper>{showEasterEgg && <EasterEgg seed={seed} />}</EggWrapper>
        <Button onClick={saveEgg}>Save your egg</Button>
        <Fireworks />
      </Content>
    </Wrapper>
  )
}

const Wrapper = styled.div`
  padding-bottom: 36px;
  color: var(--color-gray1);
  background-color: var(--color-gray12);
  min-height: 100%;
  flex-direction: column;
  display: flex;
`

const Content = styled.div`
  margin: 0 auto;
  max-width: 600px;
  display: flex;
  flex-direction: column;
  align-items: center;
`

const Title = styled.h1`
  font-size: clamp(56px, 10vw + 1rem, 100px);
  font-family: var(--font-yeseva);
  margin: 0;
  margin-top: 0.5em;
`

const Subtitle = styled.p`
  text-align: center;
  margin: 0;
  font-size: 20px;
  margin-bottom: 48px;
  padding: 0 16px;
`

const EggWrapper = styled.div`
  width: clamp(350px, 30vw + 1rem, 450px);
  display: flex;
  justify-content: center;
`

const appear = keyframes`
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
`

const Button = styled.button`
  margin-top: 36px;
  border-radius: 8px;
  border-style: none;
  color: black;
  cursor: pointer;
  font-size: 18px;
  font-weight: 500;
  height: 4rem;
  padding: 0 36px;
  text-align: center;

  opacity: 0;
  animation: ${appear} 400ms ease;
  animation-delay: 3000ms;
  animation-fill-mode: forwards;

  transition: background 200ms ease-in-out, transform 200ms ease-in-out;
  background: linear-gradient(
    50deg,
    hsl(71deg 100% 90%) 0%,
    hsl(53deg 100% 90%) 11%,
    hsl(47deg 100% 90%) 22%,
    hsl(38deg 100% 90%) 33%,
    hsl(25deg 100% 90%) 44%,
    hsl(6deg 100% 90%) 56%,
    hsl(343deg 100% 90%) 67%,
    hsl(326deg 100% 90%) 78%,
    hsl(312deg 100% 90%) 89%,
    hsl(298deg 100% 90%) 100%
  );

  &:hover {
    transform: scale(1.05);
    color: #ffffff;
    text-shadow: rgba(0, 0, 0, 0.5) 0 3px 8px;
    background: linear-gradient(
      50deg,
      hsl(71deg 100% 70%) 0%,
      hsl(53deg 100% 66%) 11%,
      hsl(47deg 100% 65%) 22%,
      hsl(38deg 100% 67%) 33%,
      hsl(25deg 100% 71%) 44%,
      hsl(6deg 100% 76%) 56%,
      hsl(343deg 100% 75%) 67%,
      hsl(326deg 100% 73%) 78%,
      hsl(312deg 100% 73%) 89%,
      hsl(298deg 100% 74%) 100%
    );
  }

  &:active {
    transform: scale(0.95);
  }
`

export default WoopWoop
