import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import { FeaturedPosts } from '../components/FeaturedPosts'
import { Projects } from '../components/Projects'
import { Spacer } from '../components/Spacer'

const Home: NextPage = () => {
  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>anton gunnarsson</Heading>
      <Spacer size={48} />
      <FeaturedPosts />
      <Spacer size={128} />
      <Projects />
      <Spacer size={400} />
    </Wrapper>
  )
}

const Wrapper = styled.div`
  width: 100%;
  height: 100%;
  color: ${({ theme }) => theme.colors.gray12};
  display: flex;
  flex-direction: column;
  align-items: center;
`

const Heading = styled.h1`
  font-family: 'Yeseva One';
  font-weight: normal;
  line-height: 0.75;
  width: min-content;

  font-size: clamp(56px, 10vw + 1rem, 156px);
`

export default Home
